// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTILaHO2GNygMbOODPZjxgmWXkv_KfTA',
    appId: '1:935126433252:web:0949a122632a6d476ddbf1',
    messagingSenderId: '935126433252',
    projectId: 'mogokya-ca875',
    authDomain: 'mogokya-ca875.firebaseapp.com',
    storageBucket: 'mogokya-ca875.appspot.com',
    measurementId: 'G-JD4CRYWDXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0ogBZpR28F29TgpLvP2FT-Dc4S58O3o',
    appId: '1:935126433252:android:ee46c3a2a177f7c56ddbf1',
    messagingSenderId: '935126433252',
    projectId: 'mogokya-ca875',
    storageBucket: 'mogokya-ca875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRdbk7xKHpqt1ujCW-lMcyoV69Srm_9Y',
    appId: '1:935126433252:ios:b3a806e18f889db96ddbf1',
    messagingSenderId: '935126433252',
    projectId: 'mogokya-ca875',
    storageBucket: 'mogokya-ca875.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcRdbk7xKHpqt1ujCW-lMcyoV69Srm_9Y',
    appId: '1:935126433252:ios:b3a806e18f889db96ddbf1',
    messagingSenderId: '935126433252',
    projectId: 'mogokya-ca875',
    storageBucket: 'mogokya-ca875.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGTILaHO2GNygMbOODPZjxgmWXkv_KfTA',
    appId: '1:935126433252:web:1fd1a806a238ff206ddbf1',
    messagingSenderId: '935126433252',
    projectId: 'mogokya-ca875',
    authDomain: 'mogokya-ca875.firebaseapp.com',
    storageBucket: 'mogokya-ca875.appspot.com',
    measurementId: 'G-P7FLJPKER8',
  );

}